import requests
from urllib.parse import quote_plus as qp

def obter_coordenadas(municipio, uf):
    municipio_encoded = qp(f"{municipio}, {uf}")

    url = f'https://nominatim.openstreetmap.org/search?q={municipio_encoded}&format=json'

    try:
        response = requests.get(url)
        response.raise_for_status()
        data = response.json()

        if data:
            lat = data[0].get('lat')
            lon = data[0].get('lon')
            return lat, lon
        
        else:
            return "", ""
        
    except requests.exceptions.RequestException:
        return "", ""

municipios_pb = [
    "Água Branca",
    "Aguiar",
    "Alagoa Grande",
    "Alagoa Nova",
    "Alagoinha",
    "Alcantil",
    "Algodão de Jandaíra",
    "Alhandra",
    "Amparo",
    "Aparecida",
    "Aracagi",
    "Arara",
    "Araruna",
    "Areia",
    "Areia de Baraúnas",
    "Assunção",
    "Baía da Traição",
    "Bananeiras",
    "Baraúna",
    "Barra de Santana",
    "Barra de São Miguel",
    "Bayeux",
    "Belém",
    "Belém de Maria",
    "Belém do Brejo do Cruz",
    "Bernardino Batista",
    "Boa Ventura",
    "Boa Vista",
    "Bom Jesus",
    "Bom Sucesso",
    "Bonito de Santa Fé",
    "Boqueirão",
    "Borborema",
    "Brejo do Cruz",
    "Brejo dos Santos",
    "Caaporã",
    "Cabaceiras",
    "Cabedelo",
    "Cachoeira dos Índios",
    "Cacimba de Dentro",
    "Cacimba de Areia",
    "Cacimbas",
    "Caicó",
    "Campina Grande",
    "Capim",
    "Caraúbas",
    "Cardoso",
    "Carrapateira",
    "Casserengue",
    "Catingueira",
    "Catolé do Rocha",
    "Conceição",
    "Conceição do Almeida",
    "Condado",
    "Conde",
    "Coxixola",
    "Cruz do Espírito Santo",
    "Cubati",
    "Cuité",
    "Cuitegi",
    "Curral de Cima",
    "Curral Velho",
    "Damião",
    "Diamante",
    "Dona Inês",
    "Duas Estradas",
    "Emas",
    "Esperança",
    "Frei Martinho",
    "Gado Bravo",
    "Guarabira",
    "Gurinhém",
    "Gurjão",
    "Ibiara",
    "Igaracy",
    "Imaculada",
    "Ingá",
    "Itabaiana",
    "Itaporanga",
    "Itaporati",
    "Itatuba",
    "Jacaraú",
    "Jacaraú",
    "Jericó",
    "João Pessoa",
    "Juarez Távora",
    "Juazeirinho",
    "Junqueirópolis",
    "Juripiranga",
    "Juru",
    "Lagoa",
    "Lagoa de Dentro",
    "Lagoa Seca",
    "Lastro",
    "Livramento",
    "Logradouro",
    "Lucena",
    "Mãe d'Água",
    "Malta",
    "Mamanguape",
    "Manaíra",
    "Marcação",
    "Mari",
    "Marizópolis",
    "Massaranduba",
    "Mataraca",
    "Matinhas",
    "Mato Grosso",
    "Maturéia",
    "Montadas",
    "Monteiro",
    "Mulungu",
    "Natuba",
    "Nazarezinho",
    "Nova Floresta",
    "Nova Olinda",
    "Nova Palmeira",
    "Olho d'Água",
    "Olivedos",
    "Ouro Velho",
    "Parari",
    "Passagem",
    "Patos",
    "Paulista",
    "Pedra Branca",
    "Pedra Lavrada",
    "Pedras de Fogo",
    "Piancó",
    "Picuí",
    "Pilar",
    "Pilões",
    "Pilõezinhos",
    "Pocinhos",
    "Poço Dantas",
    "Poço de José de Moura",
    "Pombal",
    "Prata",
    "Princesa Isabel",
    "Quixabá",
    "Remígio",
    "Riachão",
    "Riachão do Bacamarte",
    "Riacho de Santo Antônio",
    "Riacho dos Cavalos",
    "Rodolfo Fernandes",
    "São Bento",
    "São Bentinho",
    "São Domingos",
    "São Francisco",
    "São João do Rio do Peixe",
    "São João do Tigre",
    "São José da Lagoa Tapada",
    "São José de Caiana",
    "São José de Espinharas",
    "São José de Piranhas",
    "São José de Princesa",
    "São José do Bonfim",
    "São José do Brejo do Cruz",
    "São José do Sabugi",
    "São José do Seridó",
    "São José do Tigre",
    "São João do Rio do Peixe",
    "São Mamede",
    "São Miguel de Taipu",
    "São Sebastião de Lagoa de Roça",
    "São Vicente do Seridó",
    "Sapé",
    "Serra Branca",
    "Serra Redonda",
    "Serra Grande",
    "Serraria",
    "Sertãozinho",
    "Sobrado",
    "Solânea",
    "Soledade",
    "Sossêgo",
    "Sousa",
    "São João do Rio do Peixe",
    "São João do Tigre",
    "São Mamede",
    "São Miguel de Taipu",
    "São Vicente do Seridó",
    "Sapé",
    "Serra Branca",
    "Serra Redonda",
    "Serra Grande",
    "Serraria",
    "Sertãozinho",
    "Sobrado",
    "Solânea",
    "Soledade",
    "Sossêgo",
    "Sousa",
    "São João do Rio do Peixe",
    "São João do Tigre",
    "São Mamede",
    "São Miguel de Taipu",
    "São Vicente do Seridó"
]

uf = "PB"

coordenadas_municipio = {}

for municipio in municipios_pb:
    lat, lon = obter_coordenadas(municipio, uf)
    coordenadas_municipio[municipio] = (lat, lon)

    # print(f"{municipio}, Latitude {lat}, Longitude: {lon}")

contagem = 0

for municipo, (lat, lon) in coordenadas_municipio.items():
    if lat == "" and lon == "":
        contagem +=1

print(f"Número de municípios sem coordenadas encontradas: {contagem}")

